<div class="gifs-comment-block" id="emoji-picker-block" style="display: none; bottom: -298px;">
    <div class="popup-gif">
        <div class="popup-content">
            <input type="hidden" id="emoji-for-parent-comment-id" />
            <div class="body-twitter-emoji-list people">
                <ul class="emoji-list">
                    <li>&#x1f604</li>
                    <li>&#x1f603</li>
                    <li>&#x1f600</li>
                    <li>&#x1f60a</li>
                    <li>&#x263a</li>
                    <li>&#x1f609</li>
                    <li>&#x1f60d</li>
                    <li>&#x1f618</li>
                    <li>&#x1f61a</li>
                    <li>&#x1f617</li>
                    <li>&#x1f619</li>
                    <li>&#x1f61c</li>
                    <li>&#x1f61d</li>
                    <li>&#x1f61b</li>
                    <li>&#x1f633</li>
                    <li>&#x1f601</li>
                    <li>&#x1f614</li>
                    <li>&#x1f60c</li>
                    <li>&#x1f612</li>
                    <li>&#x1f61e</li>
                    <li>&#x1f623</li>
                    <li>&#x1f622</li>
                    <li>&#x1f602</li>
                    <li>&#x1f62d</li>
                    <li>&#x1f62a</li>
                    <li>&#x1f625</li>
                    <li>&#x1f630</li>
                    <li>&#x1f605</li>
                    <li>&#x1f613</li>
                    <li>&#x1f629</li>
                    <li>&#x1f62b</li>
                    <li>&#x1f628</li>
                    <li>&#x1f631</li>
                    <li>&#x1f620</li>
                    <li>&#x1f621</li>
                    <li>&#x1f624</li>
                    <li>&#x1f616</li>
                    <li>&#x1f606</li>
                    <li>&#x1f60b</li>
                    <li>&#x1f637</li>
                    <li>&#x1f60e</li>
                    <li>&#x1f634</li>
                    <li>&#x1f635</li>
                    <li>&#x1f632</li>
                    <li>&#x1f61f</li>
                    <li>&#x1f626</li>
                    <li>&#x1f627</li>
                    <li>&#x1f608</li>
                    <li>&#x1f47f</li>
                    <li>&#x1f62e</li>
                    <li>&#x1f62c</li>
                    <li>&#x1f610</li>
                    <li>&#x1f615</li>
                    <li>&#x1f62f</li>
                    <li>&#x1f636</li>
                    <li>&#x1f607</li>
                    <li>&#x1f60f</li>
                    <li>&#x1f611</li>
                    <li>&#x1f472</li>
                    <li>&#x1f473</li>
                    <li>&#x1f46e</li>
                    <li>&#x1f477</li>
                    <li>&#x1f482</li>
                    <li>&#x1f476</li>
                    <li>&#x1f466</li>
                    <li>&#x1f467</li>
                    <li>&#x1f468</li>
                    <li>&#x1f469</li>
                    <li>&#x1f474</li>
                    <li>&#x1f475</li>
                    <li>&#x1f471</li>
                    <li>&#x1f47c</li>
                    <li>&#x1f478</li>
                    <li>&#x1f63a</li>
                    <li>&#x1f638</li>
                    <li>&#x1f63b</li>
                    <li>&#x1f63d</li>
                    <li>&#x1f63c</li>
                    <li>&#x1f640</li>
                    <li>&#x1f63f</li>
                    <li>&#x1f639</li>
                    <li>&#x1f63e</li>
                    <li>&#x1f479</li>
                    <li>&#x1f47a</li>
                    <li>&#x1f648</li>
                    <li>&#x1f649</li>
                    <li>&#x1f64a</li>
                    <li>&#x1f480</li>
                    <li>&#x1f47d</li>
                    <li>&#x1f4a9</li>
                    <li>&#x1f525</li>
                    <li>&#x2728</li>
                    <li>&#x1f31f</li>
                    <li>&#x1f4ab</li>
                    <li>&#x1f4a5</li>
                    <li>&#x1f4a2</li>
                    <li>&#x1f4a6</li>
                    <li>&#x1f4a7</li>
                    <li>&#x1f4a4</li>
                    <li>&#x1f4a8</li>
                    <li>&#x1f442</li>
                    <li>&#x1f440</li>
                    <li>&#x1f443</li>
                    <li>&#x1f445</li>
                    <li>&#x1f444</li>
                    <li>&#x1f44d</li>
                    <li>&#x1f44e</li>
                    <li>&#x1f44c</li>
                    <li>&#x1f44a</li>
                    <li>&#x270a</li>
                    <li>&#x270c</li>
                    <li>&#x1f44b</li>
                    <li>&#x270b</li>
                    <li>&#x1f450</li>
                    <li>&#x1f446</li>
                    <li>&#x1f447</li>
                    <li>&#x1f449</li>
                    <li>&#x1f448</li>
                    <li>&#x1f64c</li>
                    <li>&#x1f64f</li>
                    <li>&#x261d</li>
                    <li>&#x1f44f</li>
                    <li>&#x1f4aa</li>
                    <li>&#x1f6b6</li>
                    <li>&#x1f3c3</li>
                    <li>&#x1f483</li>
                    <li>&#x1f46b</li>
                    <li>&#x1f46a</li>
                    <li>&#x1f46c</li>
                    <li>&#x1f46d</li>
                    <li>&#x1f48f</li>
                    <li>&#x1f491</li>
                    <li>&#x1f46f</li>
                    <li>&#x1f646</li>
                    <li>&#x1f645</li>
                    <li>&#x1f481</li>
                    <li>&#x1f64b</li>
                    <li>&#x1f486</li>
                    <li>&#x1f487</li>
                    <li>&#x1f485</li>
                    <li>&#x1f470</li>
                    <li>&#x1f64e</li>
                    <li>&#x1f64d</li>
                    <li>&#x1f647</li>
                    <li>&#x1f3a9</li>
                    <li>&#x1f451</li>
                    <li>&#x1f452</li>
                    <li>&#x1f45f</li>
                    <li>&#x1f45e</li>
                    <li>&#x1f461</li>
                    <li>&#x1f460</li>
                    <li>&#x1f462</li>
                    <li>&#x1f455</li>
                    <li>&#x1f454</li>
                    <li>&#x1f45a</li>
                    <li>&#x1f457</li>
                    <li>&#x1f3bd</li>
                    <li>&#x1f456</li>
                    <li>&#x1f458</li>
                    <li>&#x1f459</li>
                    <li>&#x1f4bc</li>
                    <li>&#x1f45c</li>
                    <li>&#x1f45d</li>
                    <li>&#x1f45b</li>
                    <li>&#x1f453</li>
                    <li>&#x1f380</li>
                    <li>&#x1f302</li>
                    <li>&#x1f484</li>
                    <li>&#x1f49b</li>
                    <li>&#x1f499</li>
                    <li>&#x1f49c</li>
                    <li>&#x1f49a</li>
                    <li>&#x2764</li>
                    <li>&#x1f494</li>
                    <li>&#x1f497</li>
                    <li>&#x1f493</li>
                    <li>&#x1f495</li>
                    <li>&#x1f496</li>
                    <li>&#x1f49e</li>
                    <li>&#x1f48c</li>
                    <li>&#x1f498</li>
                    <li>&#x1f48b</li>
                    <li>&#x1f48d</li>
                    <li>&#x1f48e</li>
                    <li>&#x1f464</li>
                    <li>&#x1f465</li>
                    <li>&#x1f4ac</li>
                    <li>&#x1f463</li>
                    <li>&#x1f4ad</li>
                </ul>
            </div>
            <div class="body-twitter-emoji-list nature hidden">
                <ul class="emoji-list">
                    <li>&#x1f436</li>
                    <li>&#x1f43a</li>
                    <li>&#x1f431</li>
                    <li>&#x1f42d</li>
                    <li>&#x1f439</li>
                    <li>&#x1f430</li>
                    <li>&#x1f438</li>
                    <li>&#x1f42f</li>
                    <li>&#x1f428</li>
                    <li>&#x1f43b</li>
                    <li>&#x1f437</li>
                    <li>&#x1f43d</li>
                    <li>&#x1f42e</li>
                    <li>&#x1f417</li>
                    <li>&#x1f435</li>
                    <li>&#x1f412</li>
                    <li>&#x1f434</li>
                    <li>&#x1f411</li>
                    <li>&#x1f418</li>
                    <li>&#x1f43c</li>
                    <li>&#x1f427</li>
                    <li>&#x1f426</li>
                    <li>&#x1f424</li>
                    <li>&#x1f425</li>
                    <li>&#x1f423</li>
                    <li>&#x1f414</li>
                    <li>&#x1f40d</li>
                    <li>&#x1f422</li>
                    <li>&#x1f41b</li>
                    <li>&#x1f41d</li>
                    <li>&#x1f41c</li>
                    <li>&#x1f41e</li>
                    <li>&#x1f40c</li>
                    <li>&#x1f419</li>
                    <li>&#x1f41a</li>
                    <li>&#x1f420</li>
                    <li>&#x1f41f</li>
                    <li>&#x1f42c</li>
                    <li>&#x1f433</li>
                    <li>&#x1f40b</li>
                    <li>&#x1f404</li>
                    <li>&#x1f40f</li>
                    <li>&#x1f400</li>
                    <li>&#x1f403</li>
                    <li>&#x1f405</li>
                    <li>&#x1f407</li>
                    <li>&#x1f409</li>
                    <li>&#x1f40e</li>
                    <li>&#x1f410</li>
                    <li>&#x1f413</li>
                    <li>&#x1f415</li>
                    <li>&#x1f416</li>
                    <li>&#x1f401</li>
                    <li>&#x1f402</li>
                    <li>&#x1f432</li>
                    <li>&#x1f421</li>
                    <li>&#x1f40a</li>
                    <li>&#x1f42b</li>
                    <li>&#x1f42a</li>
                    <li>&#x1f406</li>
                    <li>&#x1f408</li>
                    <li>&#x1f429</li>
                    <li>&#x1f43e</li>
                    <li>&#x1f490</li>
                    <li>&#x1f338</li>
                    <li>&#x1f337</li>
                    <li>&#x1f340</li>
                    <li>&#x1f339</li>
                    <li>&#x1f33b</li>
                    <li>&#x1f33a</li>
                    <li>&#x1f341</li>
                    <li>&#x1f343</li>
                    <li>&#x1f342</li>
                    <li>&#x1f33f</li>
                    <li>&#x1f33e</li>
                    <li>&#x1f344</li>
                    <li>&#x1f335</li>
                    <li>&#x1f334</li>
                    <li>&#x1f332</li>
                    <li>&#x1f333</li>
                    <li>&#x1f330</li>
                    <li>&#x1f331</li>
                    <li>&#x1f33c</li>
                    <li>&#x1f310</li>
                    <li>&#x1f31e</li>
                    <li>&#x1f31d</li>
                    <li>&#x1f31a</li>
                    <li>&#x1f311</li>
                    <li>&#x1f312</li>
                    <li>&#x1f313</li>
                    <li>&#x1f314</li>
                    <li>&#x1f315</li>
                    <li>&#x1f316</li>
                    <li>&#x1f317</li>
                    <li>&#x1f318</li>
                    <li>&#x1f31c</li>
                    <li>&#x1f31b</li>
                    <li>&#x1f319</li>
                    <li>&#x1f30d</li>
                    <li>&#x1f30e</li>
                    <li>&#x1f30f</li>
                    <li>&#x1f30b</li>
                    <li>&#x1f30c</li>
                    <li>&#x1f320</li>
                    <li>&#x2b50</li>
                    <li>&#x2600</li>
                    <li>&#x26c5</li>
                    <li>&#x2601</li>
                    <li>&#x26a1</li>
                    <li>&#x2614</li>
                    <li>&#x2744</li>
                    <li>&#x26c4</li>
                    <li>&#x1f300</li>
                    <li>&#x1f301</li>
                    <li>&#x1f308</li>
                    <li>&#x1f30a</li>
                </ul>
            </div>
            <div class="body-twitter-emoji-list object hidden">
                <ul class="emoji-list">
                    <li>&#x1f38d</li>
                    <li>&#x1f49d</li>
                    <li>&#x1f38e</li>
                    <li>&#x1f392</li>
                    <li>&#x1f393</li>
                    <li>&#x1f38f</li>
                    <li>&#x1f386</li>
                    <li>&#x1f387</li>
                    <li>&#x1f390</li>
                    <li>&#x1f391</li>
                    <li>&#x1f383</li>
                    <li>&#x1f47b</li>
                    <li>&#x1f385</li>
                    <li>&#x1f384</li>
                    <li>&#x1f381</li>
                    <li>&#x1f38b</li>
                    <li>&#x1f389</li>
                    <li>&#x1f38a</li>
                    <li>&#x1f388</li>
                    <li>&#x1f38c</li>
                    <li>&#x1f52e</li>
                    <li>&#x1f3a5</li>
                    <li>&#x1f4f7</li>
                    <li>&#x1f4f9</li>
                    <li>&#x1f4fc</li>
                    <li>&#x1f4bf</li>
                    <li>&#x1f4c0</li>
                    <li>&#x1f4bd</li>
                    <li>&#x1f4be</li>
                    <li>&#x1f4bb</li>
                    <li>&#x1f4f1</li>
                    <li>&#x260e</li>
                    <li>&#x1f4de</li>
                    <li>&#x1f4df</li>
                    <li>&#x1f4e0</li>
                    <li>&#x1f4e1</li>
                    <li>&#x1f4fa</li>
                    <li>&#x1f4fb</li>
                    <li>&#x1f50a</li>
                    <li>&#x1f509</li>
                    <li>&#x1f508</li>
                    <li>&#x1f507</li>
                    <li>&#x1f514</li>
                    <li>&#x1f515</li>
                    <li>&#x1f4e2</li>
                    <li>&#x1f4e3</li>
                    <li>&#x23f3</li>
                    <li>&#x231b</li>
                    <li>&#x23f0</li>
                    <li>&#x231a</li>
                    <li>&#x1f513</li>
                    <li>&#x1f512</li>
                    <li>&#x1f50f</li>
                    <li>&#x1f510</li>
                    <li>&#x1f511</li>
                    <li>&#x1f50e</li>
                    <li>&#x1f4a1</li>
                    <li>&#x1f526</li>
                    <li>&#x1f506</li>
                    <li>&#x1f505</li>
                    <li>&#x1f50c</li>
                    <li>&#x1f50b</li>
                    <li>&#x1f50d</li>
                    <li>&#x1f6c1</li>
                    <li>&#x1f6c0</li>
                    <li>&#x1f6bf</li>
                    <li>&#x1f6bd</li>
                    <li>&#x1f527</li>
                    <li>&#x1f529</li>
                    <li>&#x1f528</li>
                    <li>&#x1f6aa</li>
                    <li>&#x1f6ac</li>
                    <li>&#x1f4a3</li>
                    <li>&#x1f52b</li>
                    <li>&#x1f52a</li>
                    <li>&#x1f48a</li>
                    <li>&#x1f489</li>
                    <li>&#x1f4b0</li>
                    <li>&#x1f4b4</li>
                    <li>&#x1f4b5</li>
                    <li>&#x1f4b7</li>
                    <li>&#x1f4b6</li>
                    <li>&#x1f4b3</li>
                    <li>&#x1f4b8</li>
                    <li>&#x1f4f2</li>
                    <li>&#x1f4e7</li>
                    <li>&#x1f4e5</li>
                    <li>&#x1f4e4</li>
                    <li>&#x2709</li>
                    <li>&#x1f4e9</li>
                    <li>&#x1f4e8</li>
                    <li>&#x1f4ef</li>
                    <li>&#x1f4eb</li>
                    <li>&#x1f4ea</li>
                    <li>&#x1f4ec</li>
                    <li>&#x1f4ed</li>
                    <li>&#x1f4ee</li>
                    <li>&#x1f4e6</li>
                    <li>&#x1f4dd</li>
                    <li>&#x1f4c4</li>
                    <li>&#x1f4c3</li>
                    <li>&#x1f4d1</li>
                    <li>&#x1f4ca</li>
                    <li>&#x1f4c8</li>
                    <li>&#x1f4c9</li>
                    <li>&#x1f4dc</li>
                    <li>&#x1f4cb</li>
                    <li>&#x1f4c5</li>
                    <li>&#x1f4c6</li>
                    <li>&#x1f4c7</li>
                    <li>&#x1f4c1</li>
                    <li>&#x1f4c2</li>
                    <li>&#x2702</li>
                    <li>&#x1f4cc</li>
                    <li>&#x1f4ce</li>
                    <li>&#x2712</li>
                    <li>&#x270f</li>
                    <li>&#x1f4cf</li>
                    <li>&#x1f4d0</li>
                    <li>&#x1f4d5</li>
                    <li>&#x1f4d7</li>
                    <li>&#x1f4d8</li>
                    <li>&#x1f4d9</li>
                    <li>&#x1f4d3</li>
                    <li>&#x1f4d4</li>
                    <li>&#x1f4d2</li>
                    <li>&#x1f4da</li>
                    <li>&#x1f4d6</li>
                    <li>&#x1f516</li>
                    <li>&#x1f4db</li>
                    <li>&#x1f52c</li>
                    <li>&#x1f52d</li>
                    <li>&#x1f4f0</li>
                    <li>&#x1f3a8</li>
                    <li>&#x1f3ac</li>
                    <li>&#x1f3a4</li>
                    <li>&#x1f3a7</li>
                    <li>&#x1f3bc</li>
                    <li>&#x1f3b5</li>
                    <li>&#x1f3b6</li>
                    <li>&#x1f3b9</li>
                    <li>&#x1f3bb</li>
                    <li>&#x1f3ba</li>
                    <li>&#x1f3b7</li>
                    <li>&#x1f3b8</li>
                    <li>&#x1f47e</li>
                    <li>&#x1f3ae</li>
                    <li>&#x1f0cf</li>
                    <li>&#x1f3b4</li>
                    <li>&#x1f004</li>
                    <li>&#x1f3b2</li>
                    <li>&#x1f3af</li>
                    <li>&#x1f3c8</li>
                    <li>&#x1f3c0</li>
                    <li>&#x26bd</li>
                    <li>&#x26be</li>
                    <li>&#x1f3be</li>
                    <li>&#x1f3b1</li>
                    <li>&#x1f3c9</li>
                    <li>&#x1f3b3</li>
                    <li>&#x26f3</li>
                    <li>&#x1f6b5</li>
                    <li>&#x1f6b4</li>
                    <li>&#x1f3c1</li>
                    <li>&#x1f3c7</li>
                    <li>&#x1f3c6</li>
                    <li>&#x1f3bf</li>
                    <li>&#x1f3c2</li>
                    <li>&#x1f3ca</li>
                    <li>&#x1f3c4</li>
                    <li>&#x1f3a3</li>
                    <li>&#x2615</li>
                    <li>&#x1f375</li>
                    <li>&#x1f376</li>
                    <li>&#x1f37c</li>
                    <li>&#x1f37a</li>
                    <li>&#x1f37b</li>
                    <li>&#x1f378</li>
                    <li>&#x1f379</li>
                    <li>&#x1f377</li>
                    <li>&#x1f374</li>
                    <li>&#x1f355</li>
                    <li>&#x1f354</li>
                    <li>&#x1f35f</li>
                    <li>&#x1f357</li>
                    <li>&#x1f356</li>
                    <li>&#x1f35d</li>
                    <li>&#x1f35b</li>
                    <li>&#x1f364</li>
                    <li>&#x1f371</li>
                    <li>&#x1f363</li>
                    <li>&#x1f365</li>
                    <li>&#x1f359</li>
                    <li>&#x1f358</li>
                    <li>&#x1f35a</li>
                    <li>&#x1f35c</li>
                    <li>&#x1f372</li>
                    <li>&#x1f362</li>
                    <li>&#x1f361</li>
                    <li>&#x1f373</li>
                    <li>&#x1f35e</li>
                    <li>&#x1f369</li>
                    <li>&#x1f36e</li>
                    <li>&#x1f366</li>
                    <li>&#x1f368</li>
                    <li>&#x1f367</li>
                    <li>&#x1f382</li>
                    <li>&#x1f370</li>
                    <li>&#x1f36a</li>
                    <li>&#x1f36b</li>
                    <li>&#x1f36c</li>
                    <li>&#x1f36d</li>
                    <li>&#x1f36f</li>
                    <li>&#x1f34e</li>
                    <li>&#x1f34f</li>
                    <li>&#x1f34a</li>
                    <li>&#x1f34b</li>
                    <li>&#x1f352</li>
                    <li>&#x1f347</li>
                    <li>&#x1f349</li>
                    <li>&#x1f353</li>
                    <li>&#x1f351</li>
                    <li>&#x1f348</li>
                    <li>&#x1f34c</li>
                    <li>&#x1f350</li>
                    <li>&#x1f34d</li>
                    <li>&#x1f360</li>
                    <li>&#x1f346</li>
                    <li>&#x1f345</li>
                    <li>&#x1f33d</li>
                </ul>
            </div>
            <div class="body-twitter-emoji-list place hidden">
                <ul class="emoji-list">
                    <li>&#x1f3e0</li>
                    <li>&#x1f3e1</li>
                    <li>&#x1f3eb</li>
                    <li>&#x1f3e2</li>
                    <li>&#x1f3e3</li>
                    <li>&#x1f3e5</li>
                    <li>&#x1f3e6</li>
                    <li>&#x1f3ea</li>
                    <li>&#x1f3e9</li>
                    <li>&#x1f3e8</li>
                    <li>&#x1f492</li>
                    <li>&#x26ea</li>
                    <li>&#x1f3ec</li>
                    <li>&#x1f3e4</li>
                    <li>&#xe50a</li>
                    <li>&#x1f307</li>
                    <li>&#x1f306</li>
                    <li>&#x1f3ef</li>
                    <li>&#x1f3f0</li>
                    <li>&#x26fa</li>
                    <li>&#x1f3ed</li>
                    <li>&#x1f5fc</li>
                    <li>&#x1f5fe</li>
                    <li>&#x1f5fb</li>
                    <li>&#x1f304</li>
                    <li>&#x1f305</li>
                    <li>&#x1f303</li>
                    <li>&#x1f5fd</li>
                    <li>&#x1f309</li>
                    <li>&#x1f3a0</li>
                    <li>&#x1f3a1</li>
                    <li>&#x26f2</li>
                    <li>&#x1f3a2</li>
                    <li>&#x1f6a2</li>
                    <li>&#x26f5</li>
                    <li>&#x1f6a4</li>
                    <li>&#x1f6a3</li>
                    <li>&#x2693</li>
                    <li>&#x1f680</li>
                    <li>&#x2708</li>
                    <li>&#x1f4ba</li>
                    <li>&#x1f681</li>
                    <li>&#x1f682</li>
                    <li>&#x1f68a</li>
                    <li>&#x1f689</li>
                    <li>&#x1f69e</li>
                    <li>&#x1f686</li>
                    <li>&#x1f684</li>
                    <li>&#x1f685</li>
                    <li>&#x1f688</li>
                    <li>&#x1f687</li>
                    <li>&#x1f69d</li>
                    <li>&#x1f68b</li>
                    <li>&#x1f683</li>
                    <li>&#x1f68e</li>
                    <li>&#x1f68c</li>
                    <li>&#x1f68d</li>
                    <li>&#x1f699</li>
                    <li>&#x1f698</li>
                    <li>&#x1f697</li>
                    <li>&#x1f695</li>
                    <li>&#x1f696</li>
                    <li>&#x1f69b</li>
                    <li>&#x1f69a</li>
                    <li>&#x1f6a8</li>
                    <li>&#x1f693</li>
                    <li>&#x1f694</li>
                    <li>&#x1f692</li>
                    <li>&#x1f691</li>
                    <li>&#x1f690</li>
                    <li>&#x1f6b2</li>
                    <li>&#x1f6a1</li>
                    <li>&#x1f69f</li>
                    <li>&#x1f6a0</li>
                    <li>&#x1f69c</li>
                    <li>&#x1f488</li>
                    <li>&#x1f68f</li>
                    <li>&#x1f3ab</li>
                    <li>&#x1f6a6</li>
                    <li>&#x1f6a5</li>
                    <li>&#x26a0</li>
                    <li>&#x1f6a7</li>
                    <li>&#x1f530</li>
                    <li>&#x26fd</li>
                    <li>&#x1f3ee</li>
                    <li>&#x1f3b0</li>
                    <li>&#x2668</li>
                    <li>&#x1f5ff</li>
                    <li>&#x1f3aa</li>
                    <li>&#x1f3ad</li>
                    <li>&#x1f4cd</li>
                    <li>&#x1f6a9</li>
                    <li>&#x1f1e8;&#x1f1f3</li>
                    <li>&#x1f1e9;&#x1f1ea</li>
                    <li>&#x1f1ea;&#x1f1f8</li>
                    <li>&#x1f1eb;&#x1f1f7</li>
                    <li>&#x1f1ec;&#x1f1e7</li>
                    <li>&#x1f1ee;&#x1f1f9</li>
                    <li>&#x1f1ef;&#x1f1f5</li>
                    <li>&#x1f1f0;&#x1f1f7</li>
                    <li>&#x1f1f7;&#x1f1fa</li>
                    <li>&#x1f1fa;&#x1f1f8</li>
                </ul>
            </div>
            <div class="body-twitter-emoji-list symbol hidden">
                <ul class="emoji-list">
                    <li>&#x31;&#x20e3</li>
                    <li>&#x32;&#x20e3</li>
                    <li>&#x33;&#x20e3</li>
                    <li>&#x34;&#x20e3</li>
                    <li>&#x35;&#x20e3</li>
                    <li>&#x36;&#x20e3</li>
                    <li>&#x37;&#x20e3</li>
                    <li>&#x38;&#x20e3</li>
                    <li>&#x39;&#x20e3</li>
                    <li>&#x30;&#x20e3</li>
                    <li>&#x1f51f</li>
                    <li>&#x1f522</li>
                    <li>&#x23;&#x20e3</li>
                    <li>&#x1f523</li>
                    <li>&#x1f520</li>
                    <li>&#x1f521</li>
                    <li>&#x1f524</li>
                    <li>&#x1f1e6</li>
                    <li>&#x1f1e7</li>
                    <li>&#x1f1e8</li>
                    <li>&#x1f1e9</li>
                    <li>&#x1f1ea</li>
                    <li>&#x1f1eb</li>
                    <li>&#x1f1ec</li>
                    <li>&#x1f1ed</li>
                    <li>&#x1f1ee</li>
                    <li>&#x1f1ef</li>
                    <li>&#x1f1f0</li>
                    <li>&#x1f1f1</li>
                    <li>&#x1f1f2</li>
                    <li>&#x1f1f3</li>
                    <li>&#x1f1f4</li>
                    <li>&#x1f1f5</li>
                    <li>&#x1f1f6</li>
                    <li>&#x1f1f7</li>
                    <li>&#x1f1f8</li>
                    <li>&#x1f1f9</li>
                    <li>&#x1f1fa</li>
                    <li>&#x1f1fb</li>
                    <li>&#x1f1fc</li>
                    <li>&#x1f1fd</li>
                    <li>&#x1f1fe</li>
                    <li>&#x1f1ff</li>
                    <li>&#x2b06</li>
                    <li>&#x2b07</li>
                    <li>&#x2b05</li>
                    <li>&#x27a1</li>
                    <li>&#x2196</li>
                    <li>&#x2197</li>
                    <li>&#x2198</li>
                    <li>&#x2199</li>
                    <li>&#x2194</li>
                    <li>&#x2195</li>
                    <li>&#x1f504</li>
                    <li>&#x25c0</li>
                    <li>&#x25b6</li>
                    <li>&#x1f53c</li>
                    <li>&#x1f53d</li>
                    <li>&#x21a9</li>
                    <li>&#x21aa</li>
                    <li>&#x2139</li>
                    <li>&#x23ea</li>
                    <li>&#x23e9</li>
                    <li>&#x23eb</li>
                    <li>&#x23ec</li>
                    <li>&#x2935</li>
                    <li>&#x2934</li>
                    <li>&#x1f197</li>
                    <li>&#x1f500</li>
                    <li>&#x1f501</li>
                    <li>&#x1f502</li>
                    <li>&#x1f195</li>
                    <li>&#x1f199</li>
                    <li>&#x1f192</li>
                    <li>&#x1f193</li>
                    <li>&#x1f196</li>
                    <li>&#x1f4f6</li>
                    <li>&#x1f3a6</li>
                    <li>&#x1f201</li>
                    <li>&#x1f22f</li>
                    <li>&#x1f233</li>
                    <li>&#x1f235</li>
                    <li>&#x1f234</li>
                    <li>&#x1f232</li>
                    <li>&#x1f250</li>
                    <li>&#x1f239</li>
                    <li>&#x1f23a</li>
                    <li>&#x1f236</li>
                    <li>&#x1f21a</li>
                    <li>&#x1f6bb</li>
                    <li>&#x1f6b9</li>
                    <li>&#x1f6ba</li>
                    <li>&#x1f6bc</li>
                    <li>&#x1f6be</li>
                    <li>&#x1f6b0</li>
                    <li>&#x1f6ae</li>
                    <li>&#x1f17f</li>
                    <li>&#x267f</li>
                    <li>&#x1f6ad</li>
                    <li>&#x1f237</li>
                    <li>&#x1f238</li>
                    <li>&#x1f202</li>
                    <li>&#x24c2</li>
                    <li>&#x1f6c2</li>
                    <li>&#x1f6c4</li>
                    <li>&#x1f6c5</li>
                    <li>&#x1f6c3</li>
                    <li>&#x1f251</li>
                    <li>&#x3299</li>
                    <li>&#x3297</li>
                    <li>&#x1f191</li>
                    <li>&#x1f198</li>
                    <li>&#x1f194</li>
                    <li>&#x1f6ab</li>
                    <li>&#x1f51e</li>
                    <li>&#x1f4f5</li>
                    <li>&#x1f6af</li>
                    <li>&#x1f6b1</li>
                    <li>&#x1f6b3</li>
                    <li>&#x1f6b7</li>
                    <li>&#x1f6b8</li>
                    <li>&#x26d4</li>
                    <li>&#x2733</li>
                    <li>&#x2747</li>
                    <li>&#x274e</li>
                    <li>&#x2705</li>
                    <li>&#x2734</li>
                    <li>&#x1f49f</li>
                    <li>&#x1f19a</li>
                    <li>&#x1f4f3</li>
                    <li>&#x1f4f4</li>
                    <li>&#x1f170</li>
                    <li>&#x1f171</li>
                    <li>&#x1f18e</li>
                    <li>&#x1f17e</li>
                    <li>&#x1f4a0</li>
                    <li>&#x27bf</li>
                    <li>&#x267b</li>
                    <li>&#x2648</li>
                    <li>&#x2649</li>
                    <li>&#x264a</li>
                    <li>&#x264b</li>
                    <li>&#x264c</li>
                    <li>&#x264d</li>
                    <li>&#x264e</li>
                    <li>&#x264f</li>
                    <li>&#x2650</li>
                    <li>&#x2651</li>
                    <li>&#x2652</li>
                    <li>&#x2653</li>
                    <li>&#x26ce</li>
                    <li>&#x1f52f</li>
                    <li>&#x1f3e7</li>
                    <li>&#x1f4b9</li>
                    <li>&#x1f4b2</li>
                    <li>&#x1f4b1</li>
                    <li>&#xa9</li>
                    <li>&#xae</li>
                    <li>&#x2122</li>
                    <li>&#x274c</li>
                    <li>&#x203c</li>
                    <li>&#x2049</li>
                    <li>&#x2757</li>
                    <li>&#x2753</li>
                    <li>&#x2755</li>
                    <li>&#x2754</li>
                    <li>&#x2b55</li>
                    <li>&#x1f51d</li>
                    <li>&#x1f51a</li>
                    <li>&#x1f519</li>
                    <li>&#x1f51b</li>
                    <li>&#x1f51c</li>
                    <li>&#x1f503</li>
                    <li>&#x1f55b</li>
                    <li>&#x1f567</li>
                    <li>&#x1f550</li>
                    <li>&#x1f55c</li>
                    <li>&#x1f551</li>
                    <li>&#x1f55d</li>
                    <li>&#x1f552</li>
                    <li>&#x1f55e</li>
                    <li>&#x1f553</li>
                    <li>&#x1f55f</li>
                    <li>&#x1f554</li>
                    <li>&#x1f560</li>
                    <li>&#x1f555</li>
                    <li>&#x1f556</li>
                    <li>&#x1f557</li>
                    <li>&#x1f558</li>
                    <li>&#x1f559</li>
                    <li>&#x1f55a</li>
                    <li>&#x1f561</li>
                    <li>&#x1f562</li>
                    <li>&#x1f563</li>
                    <li>&#x1f564</li>
                    <li>&#x1f565</li>
                    <li>&#x1f566</li>
                    <li>&#x2716</li>
                    <li>&#x2795</li>
                    <li>&#x2796</li>
                    <li>&#x2797</li>
                    <li>&#x2660</li>
                    <li>&#x2665</li>
                    <li>&#x2663</li>
                    <li>&#x2666</li>
                    <li>&#x1f4ae</li>
                    <li>&#x1f4af</li>
                    <li>&#x2714</li>
                    <li>&#x2611</li>
                    <li>&#x1f518</li>
                    <li>&#x1f517</li>
                    <li>&#x27b0</li>
                    <li>&#x3030</li>
                    <li>&#x303d</li>
                    <li>&#x1f531</li>
                    <li>&#x25fc</li>
                    <li>&#x25fb</li>
                    <li>&#x25fe</li>
                    <li>&#x25fd</li>
                    <li>&#x25aa</li>
                    <li>&#x25ab</li>
                    <li>&#x1f53a</li>
                    <li>&#x1f532</li>
                    <li>&#x1f533</li>
                    <li>&#x26ab</li>
                    <li>&#x26aa</li>
                    <li>&#x1f534</li>
                    <li>&#x1f535</li>
                    <li>&#x1f53b</li>
                    <li>&#x2b1c</li>
                    <li>&#x2b1b</li>
                    <li>&#x1f536</li>
                    <li>&#x1f537</li>
                    <li>&#x1f538</li>
                    <li>&#x1f539</li>
                </ul>
            </div>
            <div class="category-menu-emoji-list">
                <span data-category="people" class="active">
                    <img draggable="false" class="emoji" alt="😆" src="http://twemoji.maxcdn.com/36x36/1f606.png">
                </span>
                <span data-category="nature" class="">
                    <img draggable="false" class="emoji" alt="🌸" src="http://twemoji.maxcdn.com/36x36/1f338.png">
                </span>
                <span data-category="object" class="">
                    <img draggable="false" class="emoji" alt="🌂" src="http://twemoji.maxcdn.com/36x36/1f302.png">
                </span>
                <span data-category="place" class="">
                    <img draggable="false" class="emoji" alt="🏨" src="http://twemoji.maxcdn.com/36x36/1f3e8.png">
                </span>
                <span data-category="symbol" class="">
                    <img draggable="false" class="emoji" alt="🔀" src="http://twemoji.maxcdn.com/36x36/1f500.png">
                </span>
            </div>
        </div>
    </div>
</div>