@extends('web.guide.layout_guide')

@section('content_child')
<div>
    <p style="text-align: center;"><span style="font-size: 24px; font-family: DFKai-SB;"><strong>個人資料保護方針</strong> </span></p>
    <p><span style="font-size: 24px;">&nbsp;</span></p>
    <p><span style="font-family: DFKai-SB;">各位客戶您好</span><span style="font-family: MingLiU;">:</span> </p>
    <p style="text-indent: 11.35pt;"><span style="font-family: MingLiU;">&nbsp; </span><span style="font-family: DFKai-SB;">關於此文件</span><span style="font-family: DFKai-SB;">，請於提供</span><span>Fun! Japan</span><span style="font-family: DFKai-SB;">個人資料前</span><span style="font-family: DFKai-SB;">閱讀一遍</span><span style="font-family: DFKai-SB;">。</span><span style="font-family: DFKai-SB;">於您同意後</span><span style="font-family: DFKai-SB;">，將提供</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">所伴生之</span><span style="font-family: DFKai-SB;">各種</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">1. </span></strong><strong><span style="font-family: DFKai-SB;">個人資料</span></strong><strong><span style="font-family: DFKai-SB;">之收集、處理及</span></strong><strong><span style="font-family: DFKai-SB;">利用目的</span></strong><strong> </strong></p>
    <p><span>&nbsp;</span></p>
    <p style="text-indent: 11.35pt;"><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">就所</span><span style="font-family: DFKai-SB;">取得</span><span style="font-family: DFKai-SB;">之客戶</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">，將以下揭</span><span style="font-family: DFKai-SB;">目的（以下</span><span style="font-family: DFKai-SB;">簡稱</span><span style="font-family: DFKai-SB;">「利用目的」）利用</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="text-indent: 11.35pt;"><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(1)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">會</span><span style="font-family: DFKai-SB;">員身份</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">利用</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">作為註冊</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">會員利用</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">時之登入</span><span style="font-family: DFKai-SB;">時及</span><span style="font-family: DFKai-SB;">登入</span><span style="font-family: DFKai-SB;">後</span><span style="font-family: DFKai-SB;">之身份認證</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">各種</span><span style="font-family: DFKai-SB;">畫面中之會員</span><span style="font-family: DFKai-SB;">資料</span><span style="font-family: DFKai-SB;">自動顯示</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(2)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">本服務所提供</span><span style="font-family: DFKai-SB;">交易之完成</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">客戶參加抽獎等活動</span><span style="font-family: DFKai-SB;">、回應客戶所詢問題、</span><span style="font-family: DFKai-SB;">由</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">向客戶提出詢問</span><span style="font-family: DFKai-SB;">、相關售後服務、</span><span style="font-family: DFKai-SB;">其他完成交易</span><span style="font-family: DFKai-SB;">所需業務。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(3)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">之廣告宣傳或行銷等</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">客戶各種</span><span style="font-family: DFKai-SB;">電子報等資訊</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">以電子</span><span style="font-family: DFKai-SB;">郵件</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">郵寄信件</span><span style="font-family: DFKai-SB;">、電話</span><span style="font-family: DFKai-SB;">等提供</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">相關</span><span style="font-family: DFKai-SB;">資料。</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">對於客戶瀏覽之內容物或廣告依客戶之</span><span style="font-family: DFKai-SB;">性別、</span><span style="font-family: DFKai-SB;">年齡</span><span style="font-family: DFKai-SB;">、居住地、</span><span style="font-family: DFKai-SB;">興趣</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">嗜好</span><span style="font-family: DFKai-SB;">等</span><span style="font-family: DFKai-SB;">個人</span><span style="font-family: DFKai-SB;">屬性或購物紀錄</span><span style="font-family: DFKai-SB;">及本服務網站</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">瀏覽</span><span style="font-family: DFKai-SB;">紀錄設定個人化資料</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">伴隨分析客戶於</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">利用内容</span><span style="font-family: DFKai-SB;">，開發新服務或改善</span><span style="font-family: DFKai-SB;">現有服務</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">進行意見調查</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">活動</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">評價</span><span style="font-family: DFKai-SB;">等</span><span style="font-family: DFKai-SB;">與</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">相關之客戶聯絡</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(4)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">回應客戶所詢問題</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">回應客戶於</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">以</span><span style="font-family: DFKai-SB;">電子</span><span style="font-family: DFKai-SB;">郵件</span><span style="font-family: DFKai-SB;">、郵</span><span style="font-family: DFKai-SB;">寄信件等所為之詢問</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(5)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">其他</span><span style="font-family: DFKai-SB;">伴隨</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">利用</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">伴隨上述</span><span>(1)</span><span style="font-family: DFKai-SB;">至</span><span>(4)</span><span style="font-family: DFKai-SB;">，就</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">判斷有</span><span style="font-family: DFKai-SB;">必要</span><span style="font-family: DFKai-SB;">而</span><span style="font-family: DFKai-SB;">利用</span><span style="font-family: DFKai-SB;">之情況</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(6)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">提供予</span><span style="font-family: DFKai-SB;">服務提供</span><span style="font-family: DFKai-SB;">人</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">依</span><span style="font-family: DFKai-SB;">「</span><span>3.</span><span style="font-family: DFKai-SB;">個人資料等</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">委託」</span><span style="font-family: DFKai-SB;">提供個人資料予</span><span style="font-family: DFKai-SB;">服務提供</span><span style="font-family: DFKai-SB;">人</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(7)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">其他</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">於個別服務</span><span style="font-family: DFKai-SB;">亦可能以未規定於上揭內容之</span><span style="font-family: DFKai-SB;">目的</span><span style="font-family: DFKai-SB;">利用</span><span style="font-family: DFKai-SB;">個人資料。於此情形時</span><span style="font-family: DFKai-SB;">，將於</span><span style="font-family: DFKai-SB;">個別服務網站</span><span style="font-family: DFKai-SB;">中登載該內容</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">2. </span></strong><strong><span style="font-family: DFKai-SB;">個人資料</span></strong><strong><span style="font-family: DFKai-SB;">之</span></strong><strong><span style="font-family: DFKai-SB;">取得方法、利用期間與地區</span></strong><strong> </strong></p>
    <p> </p>
    <p style="text-indent: 11.35pt;"><span>&nbsp; </span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">方面</span><span style="font-family: DFKai-SB;">，主要是取得</span><span style="font-family: DFKai-SB;">如下之客戶相關資料</span><span style="font-family: DFKai-SB;">。</span><span style="font-family: DFKai-SB;">將</span><span style="font-family: DFKai-SB;">取得之項目</span><span style="font-family: DFKai-SB;">為非必要</span><span style="font-family: DFKai-SB;">項目</span><span style="font-family: DFKai-SB;">，而無法取得該</span><span style="font-family: DFKai-SB;">項目</span><span style="font-family: DFKai-SB;">時</span><span style="font-family: DFKai-SB;">，可能無法提供</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">、回應</span><span style="font-family: DFKai-SB;">客戶所詢問題</span><span style="font-family: DFKai-SB;">等事宜</span><span style="font-family: DFKai-SB;">，敬請見諒</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="text-indent: 11.35pt;"><span style="font-family: MingLiU;">&nbsp; </span><span style="font-family: DFKai-SB;">再者，</span><span style="font-family: DFKai-SB;">以下</span><span style="font-family: DFKai-SB;">為</span><span style="font-family: DFKai-SB;">例示</span><span style="font-family: DFKai-SB;">，此外，依</span><span style="font-family: DFKai-SB;">資料</span><span style="font-family: DFKai-SB;">具體內容</span><span style="font-family: DFKai-SB;">亦可能有</span><span style="font-family: DFKai-SB;">未符合</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">之情形</span><span style="font-family: DFKai-SB;">，得依利用目的之差異或需求，增刪已收集之個人情報類別與項目，敬請見諒。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(1)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">客戶提供之</span><span style="font-family: DFKai-SB;">資</span><span style="font-family: DFKai-SB;">訊</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">姓名</span><span style="font-family: DFKai-SB;">、性別、</span><span style="font-family: DFKai-SB;">出</span><span style="font-family: DFKai-SB;">生年月日、居住地、使用</span><span style="font-family: DFKai-SB;">語言</span><span style="font-family: DFKai-SB;">、宗教、電子</span><span style="font-family: DFKai-SB;">信箱</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">手機信箱</span><span style="font-family: DFKai-SB;">、現在</span><span style="font-family: DFKai-SB;">身處位置相關</span><span style="font-family: DFKai-SB;">資訊及</span><span style="font-family: DFKai-SB;">意見調查表之回答資訊等客戶所提供之一切資料</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(2)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">與利用</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">有關而取得之</span><span style="font-family: DFKai-SB;">資訊</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">客戶申請</span><span>Fun! Japan</span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">之抽獎活動</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">或其他交易時之得以辨識客戶之</span><span style="font-family: DFKai-SB;">資訊，</span><span style="font-family: DFKai-SB;">與係屬附帶狀態之交易紀錄相關</span><span style="font-family: DFKai-SB;">資訊。</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">以</span><span style="font-family: DFKai-SB;">電子</span><span style="font-family: DFKai-SB;">郵件或</span><span style="font-family: DFKai-SB;">其他手段、</span><span style="font-family: DFKai-SB;">對</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">服務提供</span><span style="font-family: DFKai-SB;">人提問</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">登錄意見調查表</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">參加活動</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">輸入意見</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">評定</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">等</span><span style="font-family: DFKai-SB;">行為</span><span style="font-family: DFKai-SB;">時之發言或</span><span style="font-family: DFKai-SB;">記載</span><span style="font-family: DFKai-SB;">內容相關資訊</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(3)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">以連結為</span><span style="font-family: DFKai-SB;">契機</span><span style="font-family: DFKai-SB;">，機械上所</span><span style="font-family: DFKai-SB;">取得</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">資訊</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">客戶</span><span style="font-family: DFKai-SB;">電腦</span><span style="font-family: DFKai-SB;">連結</span><span style="font-family: DFKai-SB;">網路</span><span style="font-family: DFKai-SB;">時</span><span style="font-family: DFKai-SB;">使用</span><span style="font-family: DFKai-SB;">之</span><span>IP</span><span style="font-family: DFKai-SB;">位置</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">手機之機體辨識相關</span><span style="font-family: DFKai-SB;">資訊（</span><span style="font-family: DFKai-SB;">包含連結地點之</span><span style="font-family: DFKai-SB;">資訊）。</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">除以連結本</span><span style="font-family: DFKai-SB;">網站</span><span style="font-family: DFKai-SB;">為</span><span style="font-family: DFKai-SB;">契機取得</span><span style="font-family: DFKai-SB;">之所使用瀏覽器</span><span style="font-family: DFKai-SB;">種類</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">版本</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">作業系統</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">平台等外</span><span style="font-family: DFKai-SB;">，客戶</span><span style="font-family: DFKai-SB;">瀏覽之</span><span style="font-family: DFKai-SB;">網頁</span> <span>(URL)</span><span style="font-family: DFKai-SB;">、瀏覽</span><span style="font-family: DFKai-SB;">日期時間</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">標示或查閱</span><span style="font-family: DFKai-SB;">商品</span><span style="font-family: DFKai-SB;">等相關資訊</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">除上述外</span><span style="font-family: DFKai-SB;">，使用</span><span style="font-size: 10pt; background: white; font-family: DFKai-SB;">小型文字檔案</span><span>(cookie)</span><span style="font-family: DFKai-SB;">或</span><span style="font-size: 10pt; background: white; font-family: DFKai-SB;">網頁信號</span><span>(web beacon)</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">技術取得</span><span style="font-family: DFKai-SB;">之連結</span><span style="font-family: DFKai-SB;">資料</span><span style="font-family: DFKai-SB;">等，於每次客戶利用</span><span style="font-family: DFKai-SB;">本服務自動收集</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">保管</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">資料。</span> </p>
    <p style="margin-left: 21pt;"><span>&nbsp;</span></p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(4)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">個人資料利用期間</span><span>:</span><span style="font-family: DFKai-SB;">自客戶最新登入日起算之一年間。但帳號遭刪除時，客戶的個人資料也將</span> </p>
    <p><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: DFKai-SB;">一併被刪除。</span> </p>
    <p style="margin-left: 18pt; text-indent: -18pt;"><span>(5)<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: DFKai-SB;">個人資料利用地區</span><span>:</span><span style="font-family: DFKai-SB;">台灣、日本</span> </p>
    <p> </p>
    <p><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">3. </span></strong><strong><span style="font-family: DFKai-SB;">個人資料等</span></strong><strong><span style="font-family: DFKai-SB;">之</span></strong><strong><span style="font-family: DFKai-SB;">提供</span></strong><strong><span style="font-family: PMingLiU, serif;">/</span></strong><strong><span style="font-family: DFKai-SB;">委託</span></strong><strong> </strong></p>
    <p><span>&nbsp;</span></p>
    <p style="text-indent: 11.35pt;"><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">依</span><span style="font-family: DFKai-SB;">日本</span><span style="font-family: DFKai-SB;">國之</span><span style="font-family: DFKai-SB;">個人</span><span style="font-family: DFKai-SB;">情報</span><span style="font-family: DFKai-SB;">保護法</span><span style="font-family: DFKai-SB;">處理</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">，除</span><span style="font-family: DFKai-SB;">法令</span><span style="font-family: DFKai-SB;">規定之情況外</span><span style="font-family: DFKai-SB;">，未經客戶許可，未有將該</span><span style="font-family: DFKai-SB;">資料</span><span style="font-family: DFKai-SB;">揭露、提供予</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人之情形</span><span style="font-family: DFKai-SB;">。</span><span style="font-family: DFKai-SB;">但亦有於達成</span><span style="font-family: DFKai-SB;">利用目的</span><span style="font-family: DFKai-SB;">所需之範圍內</span><span style="font-family: DFKai-SB;">，提供</span><span style="font-family: DFKai-SB;">客戶</span><span style="font-family: DFKai-SB;">個人資料、</span><span style="font-family: DFKai-SB;">或委託處理</span><span style="font-family: DFKai-SB;">個人資料之情形。於此情形下</span><span style="font-family: DFKai-SB;">，</span><span style="font-family: DFKai-SB;">於</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人之</span><span style="font-family: DFKai-SB;">契約</span><span style="font-family: DFKai-SB;">規定將進行與本文件同樣之資料管理，適當確認</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人身份及由</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人所為之</span><span style="font-family: DFKai-SB;">管理</span><span style="font-family: DFKai-SB;">體制</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="text-indent: 11.35pt;"><span>(1) </span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">委託</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">目的</span><span style="font-family: DFKai-SB;">同於</span><span style="font-family: DFKai-SB;">「</span><span>1. </span><span style="font-family: DFKai-SB;">個人資料利用目的」</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="text-indent: 11.35pt;"><span>(2) </span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">個人檔案</span><span style="font-family: DFKai-SB;">與</span><span style="font-family: DFKai-SB;">「</span><span>2.</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">取得方法」</span><span style="font-family: DFKai-SB;">相同</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="text-indent: 11.35pt;"><span>(3) </span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">委託</span><span style="font-family: DFKai-SB;">人之範圍為</span><span style="font-family: DFKai-SB;">業務上</span><span style="font-family: DFKai-SB;">所需</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">人</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="margin-left: 10mm; text-indent: -17pt;"><span>(4) </span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">手段</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">方法</span><span style="font-family: DFKai-SB;">為</span><span style="font-family: DFKai-SB;">本服務管理</span><span style="font-family: DFKai-SB;">系統</span><span style="font-family: DFKai-SB;">、</span><span>CD-ROM</span><span style="font-family: DFKai-SB;">等</span><span style="font-family: DFKai-SB;">電子</span><span style="font-family: DFKai-SB;">媒體</span><span style="font-family: DFKai-SB;">、紙</span><span style="font-family: DFKai-SB;">面等類比</span><span style="font-family: DFKai-SB;">媒體</span><span style="font-family: DFKai-SB;">等</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="margin-left: 10mm; text-indent: -17pt;"><span>(5) </span><span style="font-family: DFKai-SB;">要求停止向</span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: DFKai-SB;">人</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">委託</span><span style="font-family: DFKai-SB;">人提供</span><span style="font-family: DFKai-SB;">資料</span><span style="font-family: DFKai-SB;">時</span><span style="font-family: DFKai-SB;">，請採取</span><span style="font-family: DFKai-SB;">「</span><span>5. </span><span style="font-family: DFKai-SB;">個人資料利用目的</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">通知、</span><span style="font-family: DFKai-SB;">揭露</span><span style="font-family: DFKai-SB;">、訂正</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">新增</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">刪除</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">利用</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">停止</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">消去</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">停止提供予</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人</span><span style="font-family: DFKai-SB;">」</span><span style="font-family: DFKai-SB;">之程序</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">4. </span></strong><strong><span style="font-family: DFKai-SB;">個人資料</span></strong><strong><span style="font-family: DFKai-SB;">之</span></strong><strong><span style="font-family: DFKai-SB;">保護</span></strong><strong> </strong></p>
    <p><span>&nbsp;</span></p>
    <p style="text-indent: 11.35pt;"><span style="font-family: MingLiU;">&nbsp; </span><span style="font-family: DFKai-SB;">就客戶所提供之</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">為適當</span><span style="font-family: DFKai-SB;">管理</span><span style="font-family: DFKai-SB;">，為防止</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">之洩漏</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">滅</span><span style="font-family: DFKai-SB;">失、</span><span style="font-family: DFKai-SB;">或毀損</span><span style="font-family: DFKai-SB;">，乃從</span><span style="font-family: DFKai-SB;">技術及管理面</span><span style="font-family: DFKai-SB;">採取適當且合理之</span><span style="font-family: DFKai-SB;">保護</span><span style="font-family: DFKai-SB;">處置</span><span style="font-family: DFKai-SB;">。</span><span style="font-family: DFKai-SB;">此外，</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">約定依係屬營運公司之</span><span style="font-family: DFKai-SB;">株式</span><span style="font-family: DFKai-SB;">會社</span><span>Fun Japan Communications</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">個人資料保護方針</span><span style="font-family: DFKai-SB;">設置</span><span style="font-family: DFKai-SB;">保護管理</span><span style="font-family: DFKai-SB;">之負責人</span><span style="font-family: DFKai-SB;">，於該負責人</span><span style="font-family: DFKai-SB;">指示</span><span style="font-family: DFKai-SB;">下，限定</span><span style="font-family: DFKai-SB;">正</span><span style="font-family: DFKai-SB;">當之</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">進行範圍</span><span style="font-family: DFKai-SB;">，嚴格進行</span><span style="font-family: DFKai-SB;">收集</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">利用</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">提供</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">管理</span><span style="font-family: PMingLiU, serif;">/</span><span style="font-family: DFKai-SB;">保護。</span> </p>
    <p><span>&nbsp;</span></p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 22.7pt; text-indent: -22.7pt;"><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">&nbsp;5. </span></strong><strong><span style="font-family: DFKai-SB;">個人資料利用目的</span></strong><strong><span style="font-family: DFKai-SB;">之</span></strong><strong><span style="font-family: DFKai-SB;">通知、</span></strong><strong><span style="font-family: DFKai-SB;">揭露</span></strong><strong><span style="font-family: DFKai-SB;">、訂正、</span></strong><strong><span style="font-family: DFKai-SB;">新增</span></strong><strong><span style="font-family: DFKai-SB;">或刪除、</span></strong><strong><span style="font-family: DFKai-SB;">或</span></strong><strong><span style="font-family: DFKai-SB;">個人資料</span></strong><strong><span style="font-family: DFKai-SB;">之利用停止</span></strong><strong><span style="font-family: DFKai-SB;">、消去</span></strong><strong><span style="font-family: DFKai-SB;">或停止提供予</span></strong><strong><span style="font-family: DFKai-SB;">第三</span></strong><strong><span style="font-family: DFKai-SB;">人</span></strong><strong> </strong></p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">客</span><span style="font-family: DFKai-SB;">戶</span><span style="font-family: DFKai-SB;">個人</span><span style="font-family: DFKai-SB;">檔案利用目的之</span><span style="font-family: DFKai-SB;">通知及客</span><span style="font-family: DFKai-SB;">戶</span><span style="font-family: DFKai-SB;">個人</span><span style="font-family: DFKai-SB;">檔案之揭露</span><span style="font-family: DFKai-SB;">、訂正、</span><span style="font-family: DFKai-SB;">新增</span><span style="font-family: DFKai-SB;">、刪除、消去</span><span style="font-family: DFKai-SB;">或停止提供予</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人之相關</span><span style="font-family: DFKai-SB;">請求</span><span style="font-family: DFKai-SB;">得自</span><span style="font-family: DFKai-SB;">「</span><span>Contact Us</span><span style="font-family: DFKai-SB;">」</span><span style="font-family: DFKai-SB;">為之</span><span style="font-family: DFKai-SB;">。</span><span style="font-family: DFKai-SB;">再者</span><span style="font-family: DFKai-SB;">，如忘記使用者</span><span>ID</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">密碼時</span><span style="font-family: DFKai-SB;">，請參照</span><span>FAQ</span><span style="font-family: DFKai-SB;">頁面</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">關於</span><span style="font-family: DFKai-SB;">刪除</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">消去</span><span style="font-family: DFKai-SB;">之程序</span><span style="font-family: DFKai-SB;">，由</span><span style="font-family: DFKai-SB;">客</span><span style="font-family: DFKai-SB;">戶本身自</span><span style="font-family: DFKai-SB;">「</span><span>FAQ</span><span style="font-family: DFKai-SB;">」</span><span style="font-family: DFKai-SB;">頁面為之或由</span><span style="font-family: DFKai-SB;">客</span><span style="font-family: DFKai-SB;">戶透過</span><span style="font-family: DFKai-SB;">「</span><span>Contact Us</span><span style="font-family: DFKai-SB;">」</span><span style="font-family: DFKai-SB;">提出請求</span><span style="font-family: DFKai-SB;">。</span><span>Fun! Japan</span><span style="font-family: DFKai-SB;">將以停止利用</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">或停止向</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人提供</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">對應之</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">客</span><span style="font-family: DFKai-SB;">戶</span><span style="font-family: DFKai-SB;">請求停止利用服務</span><span style="font-family: DFKai-SB;">或停止向</span><span style="font-family: DFKai-SB;">服務提供</span><span style="font-family: DFKai-SB;">人提供</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">時</span><span style="font-family: DFKai-SB;">，可能無法利用</span><span style="font-family: DFKai-SB;">服務</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">全部</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">一部</span><span style="font-family: DFKai-SB;">分</span><span style="font-family: DFKai-SB;">。</span><span style="font-family: DFKai-SB;">此外，</span><span style="font-family: DFKai-SB;">客</span><span style="font-family: DFKai-SB;">戶</span><span style="font-family: DFKai-SB;">長期</span><span style="font-family: DFKai-SB;">未登入時</span><span style="font-family: DFKai-SB;">，</span><span style="font-family: DFKai-SB;">客</span><span style="font-family: DFKai-SB;">戶之</span><span style="font-family: DFKai-SB;">個人</span><span style="font-family: DFKai-SB;">檔案有自動被</span><span style="font-family: DFKai-SB;">刪除</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">消</span><span style="font-family: DFKai-SB;">去之情形</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span>Fun! Japan</span><span style="font-family: DFKai-SB;">有</span><span style="font-family: DFKai-SB;">保管備份檔案，以備</span><span style="font-family: DFKai-SB;">電</span><span style="font-family: DFKai-SB;">腦故障或其他</span><span style="font-family: DFKai-SB;">不可抗力</span><span style="font-family: DFKai-SB;">或人為疏失導致之檔案</span><span style="font-family: DFKai-SB;">消失之情形。</span><span style="font-family: DFKai-SB;">該備份檔案</span><span style="font-family: DFKai-SB;">性質上</span><span style="font-family: DFKai-SB;">無法進行</span><span style="font-family: DFKai-SB;">確認等</span><span style="font-family: DFKai-SB;">程序</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">客戶利用</span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">時</span><span style="font-family: DFKai-SB;">，將視為已</span><span style="font-family: DFKai-SB;">就</span><span style="font-family: DFKai-SB;">「</span><span>5. </span><span style="font-family: DFKai-SB;">個人資料利用目的</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">通知、</span><span style="font-family: DFKai-SB;">揭露</span><span style="font-family: DFKai-SB;">、訂正、</span><span style="font-family: DFKai-SB;">新增</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">刪除</span><span style="font-family: DFKai-SB;">或個人資料之</span><span style="font-family: DFKai-SB;">利用停止、</span><span style="font-family: DFKai-SB;">消去</span><span style="font-family: DFKai-SB;">或</span><span style="font-family: DFKai-SB;">停止提供予</span><span style="font-family: DFKai-SB;">第三</span><span style="font-family: DFKai-SB;">人</span><span style="font-family: DFKai-SB;">」</span><span style="font-family: DFKai-SB;">予以同意辦理</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><strong><span>&nbsp;</span></strong></p>
    <p><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">6. </span></strong><strong><span style="font-family: DFKai-SB;">未成年</span></strong><strong><span style="font-family: DFKai-SB;">客戶之</span></strong><strong><span style="font-family: DFKai-SB;">個人資料</span></strong><strong> </strong></p>
    <p><span style="font-family: &quot;ＭＳ ゴシック&quot;;">&nbsp;</span></p>
    <p style="text-indent: 11.35pt;"><span>&nbsp; </span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">就所提供之未成年人資訊</span><span style="font-family: DFKai-SB;">，經謀求與</span><span style="font-family: DFKai-SB;">大人同様</span><span style="font-family: DFKai-SB;">之</span><span style="font-family: DFKai-SB;">保護。</span><span style="font-family: DFKai-SB;">但就依個人資料之當事人所在國或區域法令，經認定為未成年人</span><span style="font-family: DFKai-SB;">者</span><span style="font-family: DFKai-SB;">，按必要可能須得到家長同意</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p> </p>
    <p><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">7. </span></strong><strong><span style="font-family: DFKai-SB;">個人資料</span></strong><strong><span style="font-family: DFKai-SB;">相關詢問窗口</span></strong><strong> </strong></p>
    <p><span>&nbsp;</span></p>
    <p style="text-indent: 11.35pt;"><span style="font-family: MingLiU;">&nbsp; </span><span style="font-family: DFKai-SB;">關於</span><span style="font-family: DFKai-SB;">個人資料</span><span style="font-family: DFKai-SB;">之處理</span><span style="font-family: DFKai-SB;">，如有不明瞭的地方，</span><span style="font-family: DFKai-SB;">請參照求助網頁</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p><span>&nbsp;</span></p>
    <p><strong><span style="font-family: &quot;ＭＳ ゴシック&quot;;">8. </span></strong><strong><span style="font-family: DFKai-SB;">本網站</span></strong><strong><span style="font-family: DFKai-SB;">之安全</span></strong><strong> </strong></p>
    <p><span>&nbsp;</span></p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">為確保客戶</span><span style="font-family: DFKai-SB;">個人</span><span style="font-family: DFKai-SB;">檔案之</span><span style="font-family: DFKai-SB;">正確性、最新性</span><span style="font-family: DFKai-SB;">，亦有可能請客戶予以協助</span><span style="font-family: DFKai-SB;">。</span> </p>
    <p style="margin-left: 21pt;"><span>&nbsp;</span></p>
    <p style="margin-left: 21pt; text-indent: -21pt;"><span style="font-family: &quot;ＭＳ 明朝&quot;, serif;">・<span style="font-variant-numeric: normal; font-stretch: normal; font-size: 7pt; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp; </span></span><span style="font-family: DFKai-SB;">本服務</span><span style="font-family: DFKai-SB;">為確保安全</span><span style="font-family: DFKai-SB;">，以防止</span><span style="font-family: DFKai-SB;">個人</span><span style="font-family: DFKai-SB;">輸入</span><span style="font-family: DFKai-SB;">特定個人資料</span><span style="font-family: DFKai-SB;">等</span><span style="font-family: DFKai-SB;">重要資料時</span><span style="font-family: DFKai-SB;">，</span><span style="font-family: DFKai-SB;">該等</span><span style="font-family: DFKai-SB;">資料</span><span style="font-family: DFKai-SB;">遭竊取</span><span style="font-family: DFKai-SB;">、</span><span style="font-family: DFKai-SB;">受</span><span style="font-family: DFKai-SB;">阻或竄改</span><span style="font-family: DFKai-SB;">為</span><span style="font-family: DFKai-SB;">目的</span><span style="font-family: DFKai-SB;">，乃</span><span style="font-family: DFKai-SB;">使用</span><span>SSL</span><span style="font-family: DFKai-SB;">（</span><span>Secure Sockets Layer</span><span style="font-family: DFKai-SB;">）技術。</span> </p>
    <p> </p>
    <p style="text-indent: 11.35pt; text-align: right;"><span style="font-family: DFKai-SB;">以上</span> </p>
    <br>
</div>
@endsection