@extends('web.guide.layout_guide')

@section('content_child')
    <div>
        <h1>Persyaratan Penggunaan</h1>
        <p>Selamat datang di&nbsp;Fun! Japan!<br>
            “Fun! Japan”&nbsp;secara&nbsp;kolektif&nbsp;berarti sebuah proyek&nbsp;(“Proyek Fun! Japan”)&nbsp;yang&nbsp;menawarkan produk dan&nbsp;layanan melalui beragam&nbsp;sarana, termasuk situs web (termasuk, tapi tidak terbatas pada domain web&nbsp;indonesia.fun-japan.jp –&nbsp;disebut sebagai&nbsp;“Situs” – yang nantinya mungkin direvisi atau diubah untuk alasan tertentu),&nbsp;dan berusaha untuk meningkatkan ketertarikan tentang&nbsp;Jepang dengan memperkenalkan produk dan layanan&nbsp;Jepang&nbsp;ke konsumen di seluruh Asia.</p>
        <p>Badan pengatur&nbsp;Fun! Japan, Tim Fun! Japan,&nbsp;menawarkan layanan dan informasi kepada pelanggannya sesuai dengan Persyaratan Penggunaan berikut&nbsp;(“Persyaratan Penggunaan”). "Fun! Japan" dengan ini mengacu pada Proyek Fun! Japan, Situs ini,&nbsp;anggota individu, atau&nbsp;perusahaan yang menyusun Tim Fun! Japan, secara individu atau kolektif, sebagaimana&nbsp;dinyatakan&nbsp;sesuai&nbsp;konteks.</p>
        <p>Silakan baca Persyaratan Penggunaan berikut dengan saksama. Dengan menggunakan atau mengakses&nbsp;Fun! Japan, Anda, sebagai pelanggan, dianggap setuju dengan Persyaratan Penggunaan di bawah ini. Jika Anda mengakses atau membeli&nbsp;produk atau layanan dari mitra Anda melalui&nbsp;Fun! Japan&nbsp;saat&nbsp;ini atau di masa mendatang, Anda juga dianggap setuju deng<span class="Apple-tab-span" style="white-space: pre;">	</span>an ketentuan dan panduan mitra pada waktu itu tanpa memperhatikan apakah mereka disertakan di&nbsp;Situs kami. Jika ketentuan dan panduan untuk produk dan layanan mitra&nbsp;kami dan Persyaratan Penggunaan ini bertentangan, maka Persyaratan Penggunaan ini akan didahulukan.</p>
        <h2>Privasi</h2>
        <p>
        </p>
        <p>Kebijakan privasi&nbsp;diterapkan saat Anda menggunakan&nbsp;Fun! Japan.<br>
            Silakan baca kebijakan tersebut dengan saksama dan pastikan Anda memahaminya.</p>
        <h2>Komunikasi elektronik</h2>
        <p>Saat Anda menggunakan&nbsp;Fun! Japan&nbsp;atau mengirim email ke&nbsp;Fun! Japan,&nbsp;Anda akan terlibat dalam komunikasi elektronik dengan&nbsp;Fun! Japan.Anda&nbsp;setuju&nbsp;untuk menerima komunikasi dari&nbsp;Fun! Japan sebagai bagian dari pemberitahuan mengenai operasi, publikasi, atau fungsinya dengan mengirim email ke alamat email Anda yang terdaftar, menyertakan pemberitahuan di Situs, atau menggunakan sarana yang tepat lainnya via Situs. Anda dianggap setuju&nbsp;bahwa komunikasi elektronik tersebut dari&nbsp;Fun! Japan, termasuk semua perjanjian, pemberitahuan, dan pengungkapan informasi,&nbsp;telah memenuhi persyaratan hukum untuk komunikasi secara tertulis.&nbsp;</p>
        <h2>Hak Cipta</h2>
        <p>
        </p>
        <p>Semua konten yang disediakan&nbsp;via Fun! Japan (mis., karakter, grafis, logo, ikon tombol, gambar, klip&nbsp;suara, film, materi yang diunduh&nbsp;secara&nbsp;digital, dan data yang diedit)&nbsp;adalah semua properti&nbsp;Fun! Japan atau penyedia konten dan dilindungi oleh&nbsp;undang-undang hak cipta Jepang dan hukum internasional mengenai hak cipta. Semua kompilasi konten yang disediakan via&nbsp;Fun! Japan&nbsp;adalah properti eksklusif&nbsp;Fun! Japan&nbsp;dan dilindungi oleh&nbsp;undang-undang hak cipta&nbsp;Jepang dan hukum internasional mengenai hak cipta. Anda tidak boleh mencetak ulang atau memproduksi ulang informasi, gambar, dll,&nbsp;yang disediakan&nbsp;via Fun! Japan tanpa izin kami.</p>
        <h2>Lisensi dan akses ke situs</h2>
        <p>Fun! Japan&nbsp;atau penyedia konten apa pun untuk Fun! Japan memberi Anda lisensi terbatas, non-eksklusif, non-komersial, dan&nbsp;pribadi untuk menggunakan&nbsp;Fun! Japan&nbsp;mensyaratkan Anda untuk&nbsp;patuh pada&nbsp;Persyaratan Penggunaan ini&nbsp;(penugasan atau sub-lisensi tidak diizinkan). Lisensi ini tidak mencakup&nbsp;salah satu&nbsp;hal berikut: penjualan kembali atau penggunaan komersial&nbsp;Fun! Japan&nbsp;atau kontennya; pengumpulan atau penggunaan daftar produk,&nbsp;penjelasan, atau harga; penggunaan sekunder&nbsp;Fun! Japan atau kontennya; unduhan atau salinan informasi akun untuk perusahaan lain; atau penggunaan alat pengumpulan atau ekstraksi data seperti penggalian data atau robot.<br>
            Fun! Japan atau pemberi lisensi, pemasok, penerbit, pemilik hak, atau pemilik konten lain dari Japan memiliki hak yang tidak diberikan secara eksplisit oleh Persyaratan Penggunaan ini atau ketentuan lainnya. Anda tidak boleh menggandakan, membuat fotokopi, menyalin, menjual, menjual kembali, mengakses, atau jika tidak menggunakan&nbsp;Fun! Japan&nbsp;atau bagian&nbsp;apa pun di dalamnya untuk penggunaan komersial tanpa persetujuan tertulis eksplisit dari&nbsp;Fun! Japan. Anda tidak boleh membingkai atau menggunakan teknologi bingkai untuk menggabungkan logo apa pun atau informasi&nbsp;bernilai lain apa pun&nbsp;yang dimiliki oleh Fun! Japan (termasuk gambar, karakter, tata letak halaman, dan format) tanpa persetujuan tertulis eksplisit. Anda dilarang&nbsp;menyalahgunakan&nbsp;Fun! Japan,&nbsp;dan hanya boleh menggunakan&nbsp;Fun! Japan sesuai dengan hukum yang berlaku. Lisensi&nbsp;yang diberikan oleh&nbsp;Fun! Japan ini akan dibatalkan atau dihentikan atas kebijaksanaan Fun! Japan tanpa pemberitahuan,&nbsp;jika&nbsp;dalam penggunaan&nbsp;Fun! Japan Anda melanggar Persyaratan Penggunaan ini atau ketentuan yang berlaku lainnya.</p>
        <h2>Akun</h2>
        <p>
            Saat menggunakan Situs ini, Anda memahami dan setuju untuk bertanggung jawab atas akun Anda, dalam&nbsp;melindungi kata sandi Anda dan mengawasi penggunaan dan akses ke akun Anda. Jika seseorang mengakses akun Anda atau menggunakan akun Anda untuk mengakses Situs, kami akan&nbsp;memercayai ID akun tersebut dan akan&nbsp;menganggap bahwa akses telah&nbsp;dilakukan oleh Anda, dan Anda akan bertanggung jawab atas segala perilaku yang dibuat melalui akun Anda. Harap beri tahu kami segera jika Anda mencurigai atau tersadar bahwa akun Anda telah digunakan tanpa otorisasi Anda. Di&nbsp;Fun! Japan kami memiliki hak untuk menghapus salah satu dan/atau semua pengiriman Anda, menunda, dan/atau menghentikan akun Anda dengan atau tanpa pemberitahuan awal. Tanpa memperhatikan apakah pelanggaran disengaja atau karena kelalaian, biaya, kerugian, dan kerusakan yang ditimbulkan&nbsp;terkait dengan penghentian sebagai akibat dari pencurian, kehilangan, atau penggunaan&nbsp;kata sandi yang tidak resmi (seperti, tapi tidak terbatas pada: biaya investigasi, biaya tindakan pencegahan, biaya pengacara, biaya korespondensi klaim)&nbsp;tidak boleh dibebankan ke Fun! Japan. Kami memiliki hak untuk merevisi atau menghapus konten, menghentikan atau mengubah promosi atau kampanye, menolak layanan, menunda akun tanpa pemberitahuan.</p>
        <h2>Poin Fun! Japan</h2>
        <p>Poin Fun! Japan (“FP”)&nbsp;hanya bisa digunakan untuk penggunaan khusus yang&nbsp;ditunjuk oleh&nbsp;Fun! Japan, seperti untuk mengajukan permohonan kampanye pada Situs dan untuk mengakses artikel yang&nbsp;diberikan khusus untuk anggota Situs.</p>
        <p>FP dapat diperoleh dengan:&nbsp;mendaftar sebagai anggota Situs; masuk ke dalam Situs; memasukkan lotre; menjawab kuesioner; mendaftarkan halaman web yang disediakan FP sebagai favorit; berbagi halaman web&nbsp;semacam itu; mengomentari halaman web semacam itu; berpartisipasi dalam kampanye; dan metode lain yang ditunjuk oleh&nbsp;Fun! Japan.</p>
        <p>FP tidak berlaku untuk proses pembelian. Kecuali jika tidak ditunjuk, FP berlaku untuk satu tahun dari tanggal masuk log terakhir pemilik akun. Jika&nbsp;akun dihentikan, FP yang didapat melalui akun yang dihentikan&nbsp;tersebut akan menjadi tidak valid. Semua FP akan menjadi tidak valid jika Situs tertutup atau jika&nbsp;Proyek Fun! Japan dihentikan. FP tidak dapat dialihkan ke program poin lainnya. FP tidak dapat ditukar dengan uang tunai atau jenis poin lainnya dalam keadaan apa pun. FP diberikan ke akun khusus dan hanya bisa digunakan untuk akun khusus dan tidak dapat dialihkan ke akun lainnya.</p>
        <h2>Perubahan dalam Pendaftaran</h2>
        <p>Jika ada perubahan dalam pendaftaran, termasuk alamat email, Anda bertanggung jawab untuk memberi tahu kami atas perubahan tersebut. Jika pelanggan gagal untuk menyediakan atau memperbarui perihal pendaftaran dan oleh karena hal itu tidak dapat menerima layanan atau mengalami kerugian, Fun! Japan tidak akan bertanggung jawab atas kerugian tersebut.</p>
        <h2>Untuk Anak di bawah Umur</h2>
        <p>Silakan mendaftar&nbsp;setelah mendapatkan&nbsp;persetujuan dari wali sah seperti orang tua Anda. Fun! Japan memiliki hak untuk menghentikan atau menolak layanan segera jika persetujuan tersebut tidak didapatkan.</p>
        <h2>Tinjauan, komentar, komunikasi, dan konten lainnya</h2>
        <p>Sebagai pengguna&nbsp;Fun! Japan, Anda boleh mengirimkan komentar, foto, atau konten lainnya, atau mengirimkan proposal, ide, komentar, pertanyaan, atau informasi lainnya, sepanjang konten tersebut tidak ilegal, cabul, mengancam, memfitnah, mengganggu privasi, melanggar hak atas kekayaan intelektual, melukai pihak ketiga, atau pantas dipertanyakan, atau tidak berisi atau menyertakan virus perangkat lunak, kampanye politik, permintaan komersial, surat berantai, email massal, atau bentuk spam apa pun. Anda tidak boleh menggunakan alamat email yang salah, menyamar sebagai seseorang atau entitas, atau bertindak dengan cara apa pun yang bisa menyesatkan orang lain atas keaslian konten apa pun. Meski&nbsp;Fun! Japan memiliki hak (tapi bukan kewajiban) untuk menghapus atau mengedit konten tersebut, Fun! Japan tidak mengonfirmasi konten terkirim secara berkala.</p>
        <p>Kecuali situs tersebut&nbsp;menyatakan secara eksplisit, saat Anda mengirimkan konten atau mengirimkan materi, Anda telah memberi&nbsp;Fun! Japan&nbsp;hak&nbsp;non-eksklusif, tanpa-royalti, abadi, tidak dapat dibatalkan, dan sepenuhnya dapat&nbsp;dilisensikan untuk menggunakan, mereproduksi, memodifikasi, mengadaptasi, menerbitkan, menerjemahkan, membuat karya turunan, mendistribusikan, dan menampilkan konten tersebut secara global di media apa pun. Anda akan memberi&nbsp;Fun! Japan dan&nbsp;pemegang lisensinya hak untuk menggunakan nama yang telah Anda kirimkan sehubungan dengan konten tersebut, jika mereka memilih. Anda tidak akan menggunakan hak moral penulis Anda bertentangan dengan Fun! Japan atau&nbsp;pemegang lisensinya. Anda mewakili dan memberi jaminan kepada&nbsp;Fun! Japan&nbsp;bahwa Anda memiliki atau dengan cara lain mengontrol semua hak atas konten yang Anda posting; bahwa konten tersebut akurat; bahwa penggunaan konten yang Anda pasok tersebut&nbsp;tidak melanggar Persyaratan Penggunaan ini dan tidak akan menyebabkan cedera kepada orang atau entitas ketiga mana pun; dan bahwa Anda akan memberikan kompensasi kepada Fun! Japan atas semua klaim yang timbul dari konten yang Anda pasok. Fun! Japan&nbsp;tidak akan menjamin bahwa Fun! Japan akan mencatat atau menyimpan informasi&nbsp;atau materi apa pun yang dikirimkan&nbsp;atau diposting oleh Anda secara akurat, dan&nbsp;Fun! Japan&nbsp;tidak&nbsp;menanggung kewajiban&nbsp;atau bertanggung jawab atas kerugian, perubahan, atau kebocoran informasi atau materi tersebut. Fun! Japan memiliki hak, tapi bukan kewajiban, untuk memantau, mengedit, atau menghapus&nbsp;undang-undang atau konten apa pun. Fun! Japan tidak bertanggung jawab atau berasumsi tidak memiliki kewajiban atas konten apa pun yang diposting oleh Anda atau pihak ketiga mana pun.</p>
        <h2>Pemberitahuan atas pelanggaran hak atas kekayaan intelektual</h2>
        <p>Fun! Japan menghormati hak atas kekayaan intelektual orang lain. Jika Anda percaya bahwa karya Anda yang memiliki hak cipta telah difotokopi atau digunakan di Situs&nbsp;dengan metode yang merupakan pelanggaran hak cipta atau hak atas kekayaan intelektual, beri tahu kami sesuai dengan prosedur pemberitahuan atas pelanggaran hak atas kekayaan intelektual yang ditunjuk oleh&nbsp;Fun! Japan.</p>
        <h2>Deskripsi produk</h2>
        <p>Fun! Japan berusaha sebisa mungkin untuk menjaga akurasi. Namun demikian, Fun! Japan tidak menjamin bahwa deskripsi produk atau konten lainnya pada situsnya akurat, lengkap, andal, terbarui, atau bebas kesalahan. Harap perhatikan bahwa&nbsp;ketentuan ini hanya berlaku untuk produk yang dikenalkan oleh&nbsp;Fun! Japan.</p>
        <h2>Persyaratan perangkat lunak Fun! Japan</h2>
        <p>Kami merekomendasikan&nbsp;agar Anda menggunakan versi terbaru dari salah satu peramban berikut saat menggunakan&nbsp;Fun! Japan.<br>
            (Mulai 2 Juni 2014)</p>
        <ul>
            <li>Google Chrome</li>
            <li>FireFox</li>
            <li>Internet Explorer</li>
            <li>Safari</li>
        </ul>
        <h2>Pengiriman oleh pihak ketiga</h2>
        <p>
            Fun! Japan berasumsi tidak bertanggung jawab atau memiliki kewajiban atas bisnis pihak ketiga apa pun atau tindakan, produk, atau konten apa pun dari pihak ketiga. Kami merekomendasikan agar Anda membaca kebijakan atas privasi dan persyaratan penggunaan perusahaan tersebut secara saksama.</p>
        <h2>Penafian</h2>
        <p>Kecuali jika tidak disebutkan secara tertulis, Fun! Japan&nbsp;dan semua informasi, konten, materi, produk (perangkat lunak yang menyertai), dan layanan lainnya yang bisa Anda gunakan di situsnya disediakan oleh&nbsp;Fun! Japan&nbsp;secara “apa adanya”&nbsp;dan “sesuai ketersediaan”. Kecuali jika tidak disebutkan secara tertulis, Fun! Japan&nbsp;tidak membuat tipe keterwakilan garansi apa pun,&nbsp;baik tersurat maupun tersirat,&nbsp;berkenaan dengan pengoperasian&nbsp;Fun! Japan, situsnya, atau informasi, konten, materi,&nbsp;atau produk yang diposting di&nbsp;Fun! Japan. Anda dianggap secara eksplisit setuju&nbsp;untuk menggunakan situs ini dan&nbsp;Fun! Japan dengan menanggung segala risiko sendiri. Khususnya,&nbsp;Anda secara eksplisit setuju untuk&nbsp;membebaskan&nbsp;Fun! Japan dari tanggung jawab&nbsp;atas segala kerugian yang ditimbulkan dari klaim, perselisihan, atau kerusakan yang terjadi sebagai akibat dari penundaan server atau kehilangan data yang disimpan.</p>
        <p>Fun! Japan tidak dimaksudkan untuk menjadi platform yang merekomendasikan pembelian, penjualan, atau menahan produk atau jasa yang tersedia untuk pelanggan di Situsnya. Karena informasi yang ada di iklan bisa berubah, kami meminta para pelanggan untuk membuat keputusan pembelian produk berdasarkan&nbsp;pertimbangan Anda sendiri, tanpa semata-mata mengandalkan informasi sebagaimana diposting oleh&nbsp;Fun! Japan. Fun! Japan tidak bertanggung jawab, tidak akan bertindak sebagai konsultan, dan tidak akan menjadi pihak pada negosiasi kontrak mana pun antara pelanggan, tanpa memperhatikan apakah interaksi tersebut dilakukan via Situs.</p>
        <p>Fun! Japan&nbsp;tidak akan&nbsp;turut campur dalam segala diskusi atau interaksi antara pelanggan, meski keterlibatan tersebut adalah&nbsp;akibat dari pemanfaatan&nbsp;Fun! Japan&nbsp;dan/atau Situs tersebut. Tugas, pemecahan masalah, kewajiban hukum, atau komunikasi apa pun yang diakibatkan dari keterlibatan antarpelanggan adalah semata-mata tanggung jawab dari pelanggan itu sendiri. Fun! Japan&nbsp;tidak bertanggung jawab atas segala kerusakan yang diakibatkan oleh atau timbul dari informasi yang diterbitkan dari keterlibatan&nbsp;sebagai akibat dari penggunaan Situs kami&nbsp;dan/atau Fun! Japan.</p>
        <p>Fun! Japan tidak akan menawarkan jaminan apa pun (termasuk tapi tidak terbatas pada,&nbsp;jika jaminan tersebut dapat diperjualbelikan atau sesuai dengan tujuan), sampai batas kemungkinan&nbsp;diizinkan menurut undang-undang yang berlaku, untuk produk atau jasa yang bisa diperoleh, baik tersirat ataupun tersurat. Fun! Japan tidak menjamin bahwa informasi, konten, materi, produk (termasuk perangkat lunak), layanan, server, atau komunikasi email tidak terinfeksi dengan elemen atau virus berbahaya. Fun! Japan&nbsp;tidak bertanggung jawab termasuk, tapi tidak terbatas pada,&nbsp;hukuman langsung dan tidak langsung, atau kerusakan yang diakibatkan oleh penggunaan dan akses&nbsp;Fun! Japan.</p>
        <h2>Undang-undang yang mengatur</h2>
        <p>
            Dengan menggunakan&nbsp;Fun! Japan,&nbsp;Anda setuju untuk&nbsp;patuh pada hukum Jepang,&nbsp;terlepas dari konflik&nbsp;terhadap prinsip-prinsip hukum, atas segala jenis&nbsp;perselisihan yang mungkin timbul sehubungan dengan ketentuan layanan ini dan antara Anda dan&nbsp;Fun! Japan atau perusahaannya yang terkait.</p>
        <h2>Perselisihan</h2>
        <p>Selain pengadilan yurisdiksi umum yang diizinkan menurut undang-undang yang berlaku, Pengadilan Distrik Tokyo akan ditunjuk sebagai pengadilan yurisdiksi perjanjian tambahan untuk semua perselisihan yang terkait dengan akses ke&nbsp;Fun! Japan. Namun demikian, untuk pelanggan bisnis, Pengadilan Distrik Tokyo akan menjadi pengadilan yurisdiksi perjanjian eksklusif.</p>
        <h2>Kebijakan operasional situs, revisi, keterpisahan</h2>
        <p>
            Baca kebijakan operasional situs dengan saksama, termasuk kebijakan tentang harga yang diposting di situs tersebut. Kebijakan ini juga membatasi penggunaan&nbsp;Fun! Japan Anda. Fun! Japan berhak untuk merevisi situs, kebijakan, atau ketentuan layanan ini kapan saja. Jika ada ketentuan dalam persyaratan ini melanggar hukum, batal, atau atas alasan tertentu tidak dapat diterapkan, ketentuan tersebut akan dianggap dapat dipisahkan dari persyaratan ini dan tidak akan berakibat pada validitas dan keberlakuan ketentuan lainnya.</p>
        <h2>Badan Pengatur</h2>
        <p>Situs ini dikelola dan dioperasikan oleh tim relawan yang membentuk&nbsp;Fun! Japan. Dengan memperhatikan hak,&nbsp;hak istimewa, dan penafian yang disediakan untuk Fun! Japan menurut Persyaratan Penggunaan ini,&nbsp;relawan yang membentuk&nbsp;Fun! Japan&nbsp;atau perusahaan yang&nbsp;mendukung&nbsp;Fun! Japan atau petugas atau karyawan dari perusahaan-perusahaan tersebut bisa menguji atau tetap menggunakan hak, hak istimewa, dan penafian tersebut.</p>
        <h2>Pertanyaan</h2>
        <p>
            Email:  support-id@fun-japan.jp
        </p>
    </div>
@endsection
