FROM nginx:latest

MAINTAINER TungPro <mr.nttung@gmail.com>

ENV TERM xterm
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx-default.conf /etc/nginx/conf.d/default.conf
COPY nginx-upstream.conf /etc/nginx/conf.d/upstream.conf
RUN usermod -u 1000 www-data
RUN mkdir -p /var/www/laravel/public/ \
    && touch /var/www/laravel/public/index.php

CMD ["nginx"]

EXPOSE 80 443
