{!! Html::style('assets/admin/css/bootstrap.min.css') !!}
{!! Html::style('assets/admin/css/jquery-datetimepicker/jquery.datetimepicker.min.css') !!}
{!! Html::style('assets/admin/font-awesome/css/font-awesome.css') !!}
{!! Html::style('assets/admin/css/plugins/toastr/toastr.min.css') !!}
{!! Html::style('assets/admin/css/plugins/dataTables/datatables.min.css') !!}
{!! Html::style('assets/admin/css/article.css') !!}
{!! Html::style('assets/admin/css/plugins/steps/jquery.steps.css') !!}
{!! Html::style('assets/admin/css/plugins/bootstrap-markdown/bootstrap-markdown.min.css') !!}
{!! Html::style('assets/admin/css/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css') !!}
{!! Html::style('assets/admin/css/plugins/select2/select2.min.css') !!}
{!! Html::style('assets/admin/js/plugins/gritter/jquery.gritter.css') !!}
{!! Html::style('assets/admin/css/animate.css') !!}
{!! Html::style('assets/admin/css/style.css') !!}
{!! Html::style('assets/admin/css/plugins/sweetalert/sweetalert.css') !!}
{!! Html::style('assets/admin/css/plugins/select2/select2.min.css') !!}
{!! Html::style('assets/admin/css/admin.css') !!}
{!! Html::style('assets/admin/css/survey.css') !!}
{!! Html::style('assets/admin/css/plugins/datapicker/datepicker3.css') !!}
{!! Html::style('assets/admin/css/plugins/clockpicker/clockpicker.css') !!}
@yield('style')
